# Application stuff
app:
  name: CyberJobsAPI
  description: Restful backend for the CyberJobs website
# Server settings
server:
  port: 8080
  address: 0.0.0.0
# Database
spring.datasource:
  url: jdbc:postgresql://${CJ_HOST}:${CJ_PORT}/${CJ_DB}
  username: ${CJ_USER}
  password: ${CJ_PW}
# JPA
spring.jpa:
  hibernate:
    ddl-auto: none
  show-sql: false
  database-platform: org.hibernate.dialect.PostgreSQLDialect
# Swagger
springdoc.swagger-ui:
  path: /api/docs
  operationsSorter: method
# RabbitMQ
spring:
  rabbitmq:
    addresses: rabbitmq:5672